# Assignment

In [2]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [3]:
x = np.ones((5,5),dtype= int)
x = x*6
y = np.zeros((3,3))
x[1:4,1:4] = y
x

array([[6, 6, 6, 6, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [234]:
a = np.ones((8,8), dtype = int)
a = a*3
a[0::2,1::2] = a[0::2,1::2]*3
a[1::2,0::2] = a[1::2,0::2]*3
a

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [235]:
print(np.empty([3,4]))
print(np.full((3, 3), 6))

[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [4.9e-324 9.9e-324 1.5e-323 2.0e-323]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [236]:
celcius = np.array([])
input_Fah = np.array([0,12,45.21,34,99.91])
print('Values in Fahrenheit degrees-\n',input_Fah)
for i in np.nditer(input_Fah):
    i = (i-32)*(5/9)
    celcius = np.append(celcius, [i])
print('Values in Centigrade degrees-\n',celcius)

Values in Fahrenheit degrees-
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees-
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [237]:
Original_array = np.array([ 1.00000000+0.0j, 0.70710678+0.70710678j])
print('Original array ',Original_array)
# numpy.real : Return the real part of the complex argument
print('Real part of the array-\n',Original_array.real)
# numpy.imag : Return the imaginary part of the complex argument
print('Imaginary part of the array-\n',Original_array.imag)

Original array  [1.        +0.j         0.70710678+0.70710678j]
Real part of the array-
 [1.         0.70710678]
Imaginary part of the array-
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [238]:
Array1 = np.array([0,10,20,40,60])
Array2 = np.array([0,40])
print('Array1: ',Array1)
print('Array2: ',Array2)
# numpy.in1d : Test whether each element of a 1-D array is also present in a second array
print('Compare each element of array1 and array2\n',np.in1d(Array1,Array2))

Array1:  [ 0 10 20 40 60]
Array2:  [ 0 40]
Compare each element of array1 and array2
 [ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [239]:
Array1 = np.array([0,10,20,40,60])
Array2 = np.array([10,30,40])
print('Array1:',Array1)
print('Array2:',Array2)
# numpy.intersect1d : Return the sorted, unique values that are in both of the input arrays
print('Common values between two arrays-\n',np.intersect1d(Array1,Array2))

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays-
 [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [240]:
Original_array = np.array([10,10,20,20,30,30])
print('Original array-\n',Original_array)
# numpy.unique : Returns the sorted unique elements of an array
print('Unique elements of the above array-\n',np.unique(Original_array))
Original_array1 = np.array([[1,1],[2,3]])
print('Original array-\n',Original_array1)
print('Unique elements of the above array-\n',np.unique(Original_array1))

Original array-
 [10 10 20 20 30 30]
Unique elements of the above array-
 [10 20 30]
Original array-
 [[1 1]
 [2 3]]
Unique elements of the above array-
 [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [241]:
Array1 = np.array([0,10,20,40,60,80])
Array2 = np.array([10,30,40,50,70])
print('Array1 -',Array1)
print('Array2 -',Array2)
# numpy.setxor1d : Return the sorted, unique values that are in only one (not both) of the input arrays
print('Unique values that are in only one (not both) of the input arrays-\n',np.setxor1d(Array1,Array2))

Array1 - [ 0 10 20 40 60 80]
Array2 - [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays-
 [ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [242]:
test = np.array([[1,2],[1,3]])
# np.all : Test whether all array elements along a given axis evaluate to True
print(np.all(test))
# Another example
test_1 = np.array([[0,1],[2,3]])
print(np.all(test_1))

True
False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [244]:
test = np.array([[0,2],[1,3]])
# np.any : Test whether any array element along a given axis evaluates to True
print(np.any(test))
# Another example
test1 = np.array([[True, False],[False,False]])
print(np.any(test1))

True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [245]:
Sample_array = np.array([1,2,3,4])
print('Original array\n',Sample_array)
# np.tile : Construct an array by repeating another array, the number of times given by reps
print('Repeating 2 times\n',np.tile(Sample_array,2))
print('Repeating 3 times\n',np.tile(Sample_array,3))

Original array
 [1 2 3 4]
Repeating 2 times
 [1 2 3 4 1 2 3 4]
Repeating 3 times
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [246]:
Original_array = np.array([1,2,3,4,5,6])
print('Original array- ',Original_array)
# np.argmax : Returns the indices of the maximum values along an axis.
print('Maximum Values- ',np.argmax(Original_array))
# np.argmin : Returns the indices of the minimum values along an axis
print('Minimum Values- ',np.argmin(Original_array))

Original array-  [1 2 3 4 5 6]
Maximum Values-  5
Minimum Values-  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [247]:
a = np.array([1,2])
b = np.array([4,5])
print('Original array\n',a,'\n',b)
# np.greater : Return the truth value of (a > b) element-wise
print('a > b')
print(np.greater(a,b))
# np.greater_equal : Return the truth value of (a >= b) element-wise.
print('a >= b')
print(np.greater_equal(a,b))
# np.less : Return the truth value of (a > b) element-wise
print('a < b')
print(np.less(a,b))
# np.less_equal : Return the truth value of (a =< b) element-wise
print('a <= b')
print(np.less_equal(a,b))

Original array
 [1 2] 
 [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [248]:
sample_array = np.array([[4,6],[2,1]])
print('Original array\n',sample_array)
print('Sort along the first axis\n',np.sort(sample_array, axis = 0))
print('Sort along the last axis\n',np.sort(sample_array))

Original array
 [[4 6]
 [2 1]]
Sort along the first axis
 [[2 1]
 [4 6]]
Sort along the last axis
 [[4 6]
 [1 2]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [249]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
# Perform an indirect stable sort using a sequence of keys
# sorting first by first_names, then last_names
sorted_index = np.lexsort((first_names,last_names))
print(sorted_index)
# pairs
print ([(last_names[i],first_names[i]) for i in sorted_index])

[0 1 2 3 4]
[('Battle', 'Betsey'), ('Brien', 'Shelley'), ('Plotner', 'Lanell'), ('Stahl', 'Genesis'), ('Woolum', 'Margery')]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [250]:
x = np.array([[0,10,20],[20,30,40]])
print('Values bigger than 10 = {}'.format(x[x>10]))
# np.where :: Return elements chosen from x or y depending on condition
print('Their indices are {}'.format(np.where(x>10)))

Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [251]:
a = np.linspace(1,20,9).reshape(3,3)
# np.itemsize :: Length of one array element in bytes.
# np.size :: Number of elements in the array
print('Memomry size occupied by a ::{}'.format(a.size * a.itemsize))
print('-------'*5)
# OR
# np.nbytes :: Total bytes consumed by the elements of the array
print('Memomry size occupied by a ::{}'.format(a.nbytes))

Memomry size occupied by a ::72
-----------------------------------
Memomry size occupied by a ::72


## Great Job!